/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liutao62_jni_HelloNative */

#ifndef _Included_com_liutao62_jni_HelloNative
#define _Included_com_liutao62_jni_HelloNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liutao62_jni_HelloNative
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_liutao62_jni_HelloNative_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
